# Generated by Django 3.0.8 on 2020-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='qwerty@mail.ru', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
